[package]
name = "units"
version = "0.1.0"
edition = "2021"

[dependencies]
measurement_system_macro = { path = "../../proc_macros/units/measurement_system_macro" }
currency_macro = { path = "../../proc_macros/units/currency_macro" }
energy_macro = { path = "../../proc_macros/units/energy_macro" }
distance_macro = { path = "../../proc_macros/units/distance_macro" }
duration_macro = { path = "../../proc_macros/units/duration_macro" }
mass_macro = { path = "../../proc_macros/units/mass_macro" }
volume_macro = { path = "../../proc_macros/units/volume_macro" }
density_macro = { path = "../../proc_macros/units/density_macro" }
power_macro = { path = "../../proc_macros/units/power_macro" }
specific_currency_macro = { path = "../../proc_macros/units/specific_currency_macro" }
utils = { path = "../utils" }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
chrono = { version = "0.4.42", features = ["serde"] }
