[package]
name = "journal"
version = "0.1.0"
edition = "2021"

[dependencies]
exercise = { path = "../exercise" }
foods = { path = "../food_crates/foods" }
nutrients = { path = "../food_crates/nutrients" }
profiles = { path = "../profiles" }
units = { path = "../units" }
chrono = "0.4.42"
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "macro-diagnostics", "serde"] }

