[package]
name = "units"
version = "0.1.0"
edition = "2021"

[dependencies]
units_macro = { path = "../../../proc_macros/units_macro" }
utils = { path = "../utils" }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
chrono = { version = "0.4.42", features = ["serde"] }
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio", "uuid", "chrono", "macros"] }
tokio = "1.48.0"
thiserror = "2.0.18"
